<?php
// auth-generated by FilterConfigHandler
// date: 12/28/2019 22:11:34
require_once('/Users/ketter123/phpsrc/open/app/LKT/webapp/filter/LoginFilter.class.php');
require_once('/Users/ketter123/phpsrc/open/app/LKT/webapp/filter/ThdFilter.class.php');
require_once('/Users/ketter123/phpsrc/open/app/LKT/webapp/filter/SedFilter.class.php');
$filters = array();
$filter = new ExecutionTimeFilter();
$filter->initialize($this->context, array('comment' => true));
$filters[] = $filter;
$filter = new LoginFilter();
$filter->initialize($this->context, array('effect' => true));
$filters[] = $filter;
$filter = new ThdFilter();
$filter->initialize($this->context, array('effect' => true));
$filters[] = $filter;
$filter = new SedFilter();
$filter->initialize($this->context, array('effect' => true));
$filters[] = $filter;
$list[$moduleName] =& $filters;
?>