<?php
// auth-generated by ModuleConfigHandler
// date: 10/19/2019 11:49:15
define('MOD_DEFAULT_ENABLED', true);
define('MOD_DEFAULT_TITLE', 'Default Mojavi Module');
define('MOD_DEFAULT_VERSION', 1.0);
define('MOD_DEFAULT_NAME', 'Default');
define('MOD_DEFAULT_AUTHOR', 'fly');
define('MOD_DEFAULT_HOMEPAGE', null);
define('MOD_DEFAULT_UPDATE_URL', null);
define('MOD_DEFAULT_DESCRIPTION', 'Default Mojavi Module');
?>